name: deploy
# This workflow is triggered on pushes to the repository.
on: [push]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@master
      - name: Installing project dependencies
        run: |
          npm install
      - name: Check lint
        run: |
          npm run lint
      - name: Deploy to github pages on push to master
        if: github.ref == 'refs/heads/master'
        run: git push https://${{ env.GH_TOKEN }}@github.com/andythsu/WaterlooStudies.git master:gh-pages