name: deploy
# This workflow is triggered on pushes to the repository.
on: [push]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@master
      - name: Installing project dependencies
        run: |
          npm install
      - name: Check lint
        run: |
          npm run lint
      - if: github.ref == 'refs/heads/master'
        name: Deploy to github pages on push to master
        run: |
          echo "building dist"
          npm run build
          echo "switching directory to dist"
          cd dist
          git push -f git@github.com:andythsu/WaterlooStudies.git master:gh-pages
          # echo "cloning the repo"
          # git clone https://andythsu:${{ env.GH_TOKEN }}@github.com/andythsu/WaterlooStudies.git
          # echo "building "
          # git push https://${{ env.GH_TOKEN }}@github.com/andythsu/WaterlooStudies.git master:gh-pages