name: deploy
# This workflow is triggered on pushes to the repository.
on: [push]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@master
      - name: Installing project dependencies
        run: |
          npm install
      - name: Check lint
        run: |
          npm run lint
      - if: github.ref == 'refs/heads/master'
        name: Deploy to github pages
        run: |
          echo "building dist"
          npm run build
          echo "switching directory to /dist"
          cd ./dist
          git push -f https://${{ env.GH_TOKEN }}@github.com/andythsu/WaterlooStudies.git master:gh-pages